<?php

namespace AlbumBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    /**
     * findBy like function
     * @param array $params
     * @return \Doctrine\ORM\Query
     */
    public function findByQuery(array $params)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $select = $qb->select('i')->from($this->getEntityName(), 'i');

        $conditions = $this->getConditions($params);
        if (!empty($conditions)) {
            $select->where(call_user_func_array(array($qb->expr(), 'andX'), $conditions));
        }

        return $select->getQuery();
    }

    private function getConditions(array $params)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $conditions = array();
        foreach ($params as $key => $value) {
            if ($this->getClassMetadata()->hasField($key) || $this->getClassMetadata()->hasAssociation($key)) {
                $conditions[] = $qb->expr()->eq('i.'.$key, $value);
            }
        }
        return $conditions;
    }
}
